import type { Bike, FuelEntry, ServiceEntry, Ride, Modification, Checklist } from "./types";

// ---------------------------------------------------------------------------
// BikeLog stores all data as Markdown files in the user's GitHub repo.
//
// Repo layout (inside the user's selected repo):
//   bikelog/README.md                          -> auto-generated dashboard index
//   bikelog/bikes/<slug>/bike.md               -> bike profile (meta)
//   bikelog/bikes/<slug>/fuel/<date>-<odo>.md       -> one file per fuel fill
//   bikelog/bikes/<slug>/maintenance/<date>-<slug>.md -> service / repairs / issues
//   bikelog/bikes/<slug>/rides/<date>-<slug>.md     -> rides
//   bikelog/bikes/<slug>/modifications/<date>-<slug>.md
//   bikelog/bikes/<slug>/checklists/<name>.md        -> checklist templates
//   bikelog/bikes/<slug>/media/
//       bike/<name>.<ext>                          -> bike profile photos
//       <category>/<YYYY>/<MM>/<date>-<slug>.<ext> -> entry photos
//
// Every entry file uses a strict, human-readable Markdown structure so it can
// be edited by hand AND round-tripped back into the app:
//
//   # Fuel · 2026-09-01
//
//   <sub>Auto-generated by BikeLog · edit with care, format is strict</sub>
//
//   <!-- bikelog:fuel -->
//   - id: f1
//   - bikeId: 5f8e...
//   - date: 2026-09-01T00:00:00.000Z
//   - odometer: 42381
//   - litres: 8.2
//   ...
// ---------------------------------------------------------------------------

export const slugify = (s: string): string =>
  s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "bike";

export const bikeSlug = (name: string): string => slugify(name);

/** A short, filename-safe slug for an entry's distinguishing label. */
const labelSlug = (s: string): string => slugify(s);

const fmtDate = (iso: string) => (iso ? new Date(iso).toISOString().slice(0, 10) : "");

// ---- path helpers ----

export const bikeDir = (slug: string) => `bikelog/bikes/${slug}`;
export const mediaDir = (slug: string) => `${bikeDir(slug)}/media`;

/** Relative path for the bike's media file (profile photos). */
export const bikeMediaPath = (slug: string, name: string): string =>
  `${mediaDir(slug)}/bike/${name}`;

/** Relative path for an entry's media file: <category>/<YYYY>/<MM>/<name>. */
export const entryMediaPath = (slug: string, category: string, date: string, name: string): string => {
  const d = fmtDate(date);
  const [y, m] = [d.slice(0, 4), d.slice(5, 7)];
  return `${mediaDir(slug)}/${category}/${y || "0000"}/${m || "00"}/${name}`;
};

function entryFilePath(slug: string, dir: string, date: string, label: string, id: string, used: Set<string>): string {
  const base = dir === "checklists"
    ? `${label}.md`
    : `${fmtDate(date) || "unknown"}-${label}.md`;
  let path = `${bikeDir(slug)}/${dir}/${base}`;
  const seen = used.has(path);
  used.add(path);
  if (seen) {
    path = path.replace(/\.md$/, `-${id.slice(-5)}.md`);
    used.add(path);
  }
  return path;
}

export function fuelFilePath(slug: string, f: FuelEntry, used: Set<string>): string {
  return entryFilePath(slug, "fuel", f.date, String(f.odometer || 0), f.id, used);
}

export function serviceFilePath(slug: string, s: ServiceEntry, used: Set<string>): string {
  const label = labelSlug(s.items?.[0] || s.title || s.type || "service");
  return entryFilePath(slug, "maintenance", s.date, label, s.id, used);
}

export function rideFilePath(slug: string, r: Ride, used: Set<string>): string {
  const label = labelSlug(r.route || "ride");
  return entryFilePath(slug, "rides", r.date, label, r.id, used);
}

export function modificationFilePath(slug: string, m: Modification, used: Set<string>): string {
  const label = labelSlug(m.title || "mod");
  return entryFilePath(slug, "modifications", m.date, label, m.id, used);
}

export function checklistFilePath(slug: string, c: Checklist, used: Set<string>): string {
  const label = labelSlug(c.name || "checklist");
  return entryFilePath(slug, "checklists", c.createdAt || "", label, c.id, used);
}

// ---- small line-based markdown serializer/parser (no deps) ----

function propLines(obj: Record<string, unknown>): string {
  return Object.entries(obj)
    .filter(([, v]) => v !== undefined && v !== null && v !== "")
    .map(([k, v]) => `- ${k}: ${String(v)}`)
    .join("\n");
}

interface ParsedEntry {
  category: string;
  props: Record<string, string>;
}

/** Parse `<!-- bikelog:category -->` + `- key: value` props. */
function parseEntryMarkdown(md: string): ParsedEntry | null {
  const category = md.match(/<!--\s*bikelog:(\w+)\s*-->/)?.[1];
  if (!category) return null;
  const props: Record<string, string> = {};
  const start = md.indexOf(`bikelog:${category}`);
  const propsStart = md.indexOf("\n", start);
  const body = propsStart === -1 ? "" : md.slice(propsStart + 1);
  for (const line of body.split("\n")) {
    const m = line.match(/^-\s+(.+?):\s*(.*)$/);
    if (m) props[m[1]] = m[2];
  }
  return { category, props };
}

const num = (s: string | undefined, d = 0) => (s ? Number(s) : d);
const isTrue = (s: string | undefined) => s === "true" || s === "1";
const splitList = (s: string | undefined) => (s ? s.split(",").map((x) => x.trim()).filter(Boolean) : []);

// ---- entry → markdown ----

function entryToMarkdown(title: string, category: string, props: Record<string, unknown>): string {
  return [
    `# ${title}`,
    "",
    "<sub>Auto-generated by BikeLog · edit with care, format is strict</sub>",
    "",
    `<!-- bikelog:${category} -->`,
    propLines(props),
    "",
  ].join("\n");
}

export function fuelToMarkdown(f: FuelEntry): string {
  return entryToMarkdown(`Fuel · ${fmtDate(f.date) || "no date"}`, "fuel", {
    id: f.id,
    bikeId: f.bikeId,
    date: f.date,
    odometer: f.odometer,
    litres: f.litres,
    pricePerLitre: f.pricePerLitre,
    totalCost: f.totalCost,
    isFullTank: f.isFullTank,
    station: f.station,
    notes: f.notes,
  });
}

export function serviceToMarkdown(s: ServiceEntry): string {
  return entryToMarkdown(
    s.type === "issue"
      ? `Issue · ${s.title || fmtDate(s.date) || "no date"}`
      : `Service · ${fmtDate(s.date) || "no date"}`,
    "service",
    {
      id: s.id,
      bikeId: s.bikeId,
      date: s.date,
      odometer: s.odometer,
      type: s.type,
      items: (s.items ?? []).join(","),
      cost: s.cost,
      workshop: s.workshop,
      notes: s.notes,
      nextServiceKm: s.nextServiceKm,
      nextServiceDate: s.nextServiceDate,
      title: s.title,
      description: s.description,
      severity: s.severity,
      status: s.status,
      estimatedCost: s.estimatedCost,
      actualCost: s.actualCost,
    }
  );
}

export function rideToMarkdown(r: Ride): string {
  return entryToMarkdown(`Ride · ${fmtDate(r.date) || "no date"}`, "ride", {
    id: r.id,
    bikeId: r.bikeId,
    date: r.date,
    route: r.route,
    distanceKm: r.distanceKm,
    odometer: r.odometer,
    avgSpeedKmh: r.avgSpeedKmh,
    notes: r.notes,
  });
}

export function modificationToMarkdown(m: Modification): string {
  return entryToMarkdown(`Mod · ${m.title || fmtDate(m.date) || "no date"}`, "modification", {
    id: m.id,
    bikeId: m.bikeId,
    date: m.date,
    title: m.title,
    description: m.description,
    cost: m.cost,
    installedBy: m.installedBy,
    notes: m.notes,
  });
}

export function checklistToMarkdown(c: Checklist): string {
  return entryToMarkdown(`Checklist · ${c.name}`, "checklist", {
    id: c.id,
    bikeId: c.bikeId,
    name: c.name,
    items: (c.items ?? []).join(","),
    createdAt: c.createdAt,
  });
}

// ---- markdown → entry ----

export function markdownToFuel(md: string): FuelEntry | null {
  const p = parseEntryMarkdown(md);
  if (!p || p.category !== "fuel" || !p.props.id) return null;
  return {
    id: p.props.id,
    bikeId: p.props.bikeId || "",
    date: p.props.date || new Date().toISOString(),
    odometer: num(p.props.odometer),
    litres: num(p.props.litres),
    pricePerLitre: num(p.props.pricePerLitre),
    totalCost: p.props.totalCost !== undefined ? num(p.props.totalCost) : num(p.props.cost),
    isFullTank: isTrue(p.props.isFullTank) ?? isTrue(p.props.full),
    station: p.props.station || undefined,
    notes: p.props.notes || undefined,
  };
}

export function markdownToService(md: string): ServiceEntry | null {
  const p = parseEntryMarkdown(md);
  if (!p || p.category !== "service" || !p.props.id) return null;
  const type = (p.props.type as ServiceEntry["type"]) || "general";
  return {
    id: p.props.id,
    bikeId: p.props.bikeId || "",
    date: p.props.date || new Date().toISOString(),
    odometer: num(p.props.odometer),
    type,
    items: splitList(p.props.items),
    cost: num(p.props.cost),
    workshop: p.props.workshop || undefined,
    notes: p.props.notes || undefined,
    nextServiceKm: p.props.nextServiceKm ? num(p.props.nextServiceKm) : undefined,
    nextServiceDate: p.props.nextServiceDate || undefined,
    title: p.props.title || undefined,
    description: p.props.description || undefined,
    severity: (p.props.severity as ServiceEntry["severity"]) || undefined,
    status: (p.props.status as ServiceEntry["status"]) || undefined,
    estimatedCost: p.props.estimatedCost ? num(p.props.estimatedCost) : undefined,
    actualCost: p.props.actualCost ? num(p.props.actualCost) : undefined,
  };
}

export function markdownToRide(md: string): Ride | null {
  const p = parseEntryMarkdown(md);
  if (!p || p.category !== "ride" || !p.props.id) return null;
  return {
    id: p.props.id,
    bikeId: p.props.bikeId || "",
    date: p.props.date || new Date().toISOString(),
    route: p.props.route || "",
    distanceKm: num(p.props.distanceKm),
    odometer: p.props.odometer ? num(p.props.odometer) : undefined,
    avgSpeedKmh: p.props.avgSpeedKmh ? num(p.props.avgSpeedKmh) : undefined,
    notes: p.props.notes || undefined,
  };
}

export function markdownToModification(md: string): Modification | null {
  const p = parseEntryMarkdown(md);
  if (!p || p.category !== "modification" || !p.props.id) return null;
  return {
    id: p.props.id,
    bikeId: p.props.bikeId || "",
    date: p.props.date || new Date().toISOString(),
    title: p.props.title || "",
    description: p.props.description || undefined,
    cost: p.props.cost ? num(p.props.cost) : undefined,
    installedBy: p.props.installedBy || undefined,
    notes: p.props.notes || undefined,
  };
}

export function markdownToChecklist(md: string): Checklist | null {
  const p = parseEntryMarkdown(md);
  if (!p || p.category !== "checklist" || !p.props.id) return null;
  return {
    id: p.props.id,
    bikeId: p.props.bikeId || "",
    name: p.props.name || "",
    items: splitList(p.props.items),
    createdAt: p.props.createdAt || new Date().toISOString(),
  };
}

// ---- legacy single-file-per-bike format (0.0.1) ----

interface LegacyBlock {
  title: string;
  props: Record<string, string>;
}

/** Parse a legacy `bikes/<slug>.md` (sections: meta/fuel/service/issues). */
function legacyParse(md: string): { meta: Record<string, string>; blocks: Record<string, LegacyBlock[]> } {
  const lines = md.split("\n");
  const blocks: Record<string, LegacyBlock[]> = {};
  let currentSection: string | null = null;
  let currentBlock: LegacyBlock | null = null;

  for (const line of lines) {
    const marker = line.match(/^<!--\s*bikelog:(\w+)\s*-->/);
    if (marker) {
      currentSection = marker[1];
      if (currentSection === "meta") {
        currentBlock = { title: "meta", props: {} };
        blocks[currentSection] = [currentBlock];
      } else {
        currentBlock = null;
      }
      continue;
    }
    if (!currentSection) continue;
    const head = line.match(/^###\s+(.*)$/);
    const prop = line.match(/^-\s+(.+?):\s*(.*)$/);
    if (head) {
      currentBlock = { title: head[1], props: {} };
      blocks[currentSection] = blocks[currentSection] ?? [];
      blocks[currentSection].push(currentBlock);
      continue;
    }
    if (prop && currentBlock) currentBlock.props[prop[1]] = prop[2];
  }
  return { meta: blocks["meta"]?.[0]?.props ?? {}, blocks };
}

/** Parse and convert a legacy 0.0.1 `bikes/<slug>.md` into the new model. */
export function legacyMarkdownToBike(md: string): {
  bike: Bike | null;
  fuel: FuelEntry[];
  service: ServiceEntry[];
  rides: Ride[];
  modifications: Modification[];
  checklists: Checklist[];
} {
  const { meta, blocks } = legacyParse(md);
  if (!meta.id || !meta.name) return { bike: null, fuel: [], service: [], rides: [], modifications: [], checklists: [] };

  const bike: Bike = {
    id: meta.id,
    name: meta.name,
    brand: meta.brand || "",
    model: meta.model || "",
    year: num(meta.year, 0),
    odometer: num(meta.odometer, 0),
    fuelType: meta.fuelType === "diesel" ? "diesel" : "petrol",
    createdAt: meta.createdAt || new Date().toISOString(),
    photos: meta.photos ? meta.photos.split(",").map((p) => p.trim()).filter(Boolean) : [],
  };
  const bikeId = bike.id;

  const fuel: FuelEntry[] = (blocks["fuel"] ?? [])
    .map((b) => {
      const p = b.props;
      if (!p.id) return null;
      return {
        id: p.id,
        bikeId: p.bikeId || bikeId,
        date: p.date || new Date().toISOString(),
        odometer: num(p.odometer),
        litres: num(p.litres),
        pricePerLitre: num(p.pricePerLitre),
        totalCost: p.totalCost !== undefined ? num(p.totalCost) : num(p.cost),
        isFullTank: isTrue(p.isFullTank) ?? isTrue(p.full),
        station: p.station || undefined,
        notes: p.notes || undefined,
      } as FuelEntry;
    })
    .filter((x): x is FuelEntry => x !== null);

  const service: ServiceEntry[] = (blocks["service"] ?? []).map((b) => {
    const p = b.props;
    return {
      id: p.id,
      bikeId: p.bikeId || bikeId,
      date: p.date || new Date().toISOString(),
      odometer: num(p.odometer),
      type: (p.type as ServiceEntry["type"]) || "general",
      items: splitList(p.items),
      cost: num(p.cost),
      workshop: p.workshop || undefined,
      notes: p.notes || undefined,
      nextServiceKm: p.nextServiceKm ? num(p.nextServiceKm) : undefined,
      nextServiceDate: p.nextServiceDate || undefined,
    } as ServiceEntry;
  });

  // Legacy issues → maintenance entries with type "issue".
  const issues: ServiceEntry[] = (blocks["issues"] ?? []).map((b) => {
    const p = b.props;
    return {
      id: p.id,
      bikeId: p.bikeId || bikeId,
      date: p.date || new Date().toISOString(),
      odometer: num(p.odometer),
      type: "issue",
      items: [],
      cost: p.actualCost ? num(p.actualCost) : p.estimatedCost ? num(p.estimatedCost) : 0,
      title: p.title || p.description || "",
      description: p.description || p.title || "",
      severity: (p.severity as ServiceEntry["severity"]) || "low",
      status: (p.status as ServiceEntry["status"]) || "reported",
      estimatedCost: p.estimatedCost ? num(p.estimatedCost) : undefined,
      actualCost: p.actualCost ? num(p.actualCost) : undefined,
      notes: p.notes || undefined,
    } as ServiceEntry;
  });

  return {
    bike,
    fuel,
    service: [...service, ...issues],
    rides: [],
    modifications: [],
    checklists: [],
  };
}

// ---- bike profile (meta) file ----

export function bikeToMarkdown(bike: Bike): string {
  return [
    `# ${bike.name}`,
    "",
    "<sub>Auto-generated by BikeLog · edit with care, format is strict</sub>",
    "",
    "<!-- bikelog:bike -->",
    propLines({
      id: bike.id,
      name: bike.name,
      brand: bike.brand,
      model: bike.model,
      year: bike.year,
      odometer: bike.odometer,
      fuelType: bike.fuelType,
      createdAt: bike.createdAt,
      photos: (bike.photos ?? []).join(","),
    }),
    "",
  ].join("\n");
}

export function markdownToBike(md: string): Bike | null {
  const p = parseEntryMarkdown(md);
  if (!p || p.category !== "bike" || !p.props.id || !p.props.name) return null;
  return {
    id: p.props.id,
    name: p.props.name,
    brand: p.props.brand || "",
    model: p.props.model || "",
    year: num(p.props.year, 0),
    odometer: num(p.props.odometer, 0),
    fuelType: p.props.fuelType === "diesel" ? "diesel" : "petrol",
    createdAt: p.props.createdAt || new Date().toISOString(),
    photos: p.props.photos ? p.props.photos.split(",").map((p2) => p2.trim()).filter(Boolean) : [],
  };
}

// ---- README.md (dashboard index) ----

export function readmeToMarkdown(
  bikes: Bike[],
  data: {
    fuel: FuelEntry[];
    service: ServiceEntry[];
    rides: Ride[];
    modifications: Modification[];
    checklists: Checklist[];
  }
): string {
  const byBike = (bikeId: string) => ({
    fuel: data.fuel.filter((f) => f.bikeId === bikeId),
    service: data.service.filter((s) => s.bikeId === bikeId),
    rides: data.rides.filter((r) => r.bikeId === bikeId),
    mods: data.modifications.filter((m) => m.bikeId === bikeId),
    checklists: data.checklists.filter((c) => c.bikeId === bikeId),
  });

  const lines: string[] = [
    "# BikeLog",
    "",
    "> Mileage, fuel, service, rides, modifications and checklists — data lives in this repo as Markdown.",
    "",
    "## Bikes",
    "",
  ];

  if (bikes.length === 0) {
    lines.push("_No bikes yet._");
  } else {
    for (const b of bikes) {
      const slug = bikeSlug(b.name);
      const { fuel, service, rides, mods, checklists } = byBike(b.id);
      const sortedFuel = [...fuel].sort((a, c) => a.odometer - c.odometer);
      const totalKm =
        sortedFuel.length >= 2
          ? Math.max(0, sortedFuel[sortedFuel.length - 1].odometer - sortedFuel[0].odometer)
          : b.odometer;
      const lastService = [...service].sort((a, c) => a.date.localeCompare(c.date)).pop();
      const openIssues = service.filter((s) => s.type === "issue" && s.status !== "resolved");

      lines.push(
        `### ${b.name} · [\`${slug}/\`](bikes/${slug}/)`,
        "",
        `- **Odometer:** ${b.odometer} km`,
        `- **Total KM (fills):** ${totalKm} km`,
        `- **Fuel fills:** ${fuel.length}`,
        `- **Rides:** ${rides.length}`,
        `- **Modifications:** ${mods.length}`,
        `- **Checklists:** ${checklists.length}`,
        `- **Last service:** ${lastService ? fmtDate(lastService.date) : "never"}${lastService?.nextServiceKm ? ` · next at ${lastService.nextServiceKm} km` : ""}`,
        `- **Open issues:** ${openIssues.length}`,
        ""
      );
    }
  }

  lines.push("---", "", `<sub>Generated ${new Date().toISOString()} by BikeLog.</sub>`, "");
  return lines.join("\n");
}