import assert from "node:assert/strict";
import {
  bikeToMarkdown,
  markdownToBike,
  fuelToMarkdown,
  markdownToFuel,
  serviceToMarkdown,
  markdownToService,
  rideToMarkdown,
  markdownToRide,
  modificationToMarkdown,
  markdownToModification,
  checklistToMarkdown,
  markdownToChecklist,
} from "../src/lib/mdstore";

const slug = "badal";

console.log("# YAML frontmatter round-trips\n");

// ---- bike ----
const bike = {
  id: "bk1",
  name: "Badal",
  brand: "Hero",
  model: "xpulse 210",
  year: 2025,
  odometer: 4455,
  fuelType: "petrol" as const,
  createdAt: "2026-09-08T11:19:32.100Z",
  photos: [`bikelog/bikes/${slug}/media/bike/photo-1.webp`],
};
const bikeMd = bikeToMarkdown(bike);
console.log("--- bike.md ---\n" + bikeMd);
const bike2 = markdownToBike(bikeMd);
assert.ok(bike2, "bike parses");
assert.equal(bike2.id, bike.id);
assert.deepEqual(bike2.photos, bike.photos);

// ---- fuel (user's exact example shape) ----
const fuel = {
  id: "f1",
  bikeId: "bk1",
  date: "2026-09-08T00:00:00.000Z",
  odometer: 42520,
  litres: 8.72,
  pricePerLitre: 103.2,
  totalCost: 899.9,
  isFullTank: true,
  station: "HP Petrol Pump",
  notes: "Filled before highway ride.",
  photos: [`bikelog/bikes/${slug}/media/fuel/2026/09/2026-09-08-42520.webp`],
};
const fuelMd = fuelToMarkdown(fuel, slug);
console.log("--- fuel ---\n" + fuelMd);
assert.match(fuelMd, /^---\ntype: fuel\n/);
assert.match(fuelMd, /price_per_litre: 103.2\n/);
assert.match(fuelMd, /total: 899.9\n/);
assert.match(fuelMd, /full_tank: true\n/);
assert.match(fuelMd, /fuel_station: HP Petrol Pump\n/);
assert.match(fuelMd, /receipt: \.\.\/media\/fuel\/2026\/09\/2026-09-08-42520\.webp\n/);
assert.match(fuelMd, /\n\nFilled before highway ride\.\n$/);
const fuel2 = markdownToFuel(fuelMd, slug);
assert.ok(fuel2, "fuel parses");
assert.equal(fuel2.odometer, 42520);
assert.equal(fuel2.litres, 8.72);
assert.equal(fuel2.pricePerLitre, 103.2);
assert.equal(fuel2.totalCost, 899.9);
assert.equal(fuel2.isFullTank, true);
assert.equal(fuel2.station, "HP Petrol Pump");
assert.equal(fuel2.notes, "Filled before highway ride.");
assert.deepEqual(fuel2.photos, fuel.photos);

// ---- service ----
const service = {
  id: "s1",
  bikeId: "bk1",
  date: "2026-08-10",
  odometer: 41000,
  type: "scheduled" as const,
  items: ["Oil change", "Chain service"],
  cost: 1200,
  workshop: "KTM Service Center",
  notes: "Run-in service.",
  nextServiceKm: 50000,
  nextServiceDate: "2027-02-10",
};
const serviceMd = serviceToMarkdown(service, slug);
console.log("--- service ---\n" + serviceMd);
assert.match(serviceMd, /^---\ntype: scheduled\n/);
assert.match(serviceMd, /items: Oil change, Chain service\n/);
assert.match(serviceMd, /next_service_km: 50000\n/);
const service2 = markdownToService(serviceMd, slug);
assert.ok(service2, "service parses");
assert.equal(service2.type, "scheduled");
assert.deepEqual(service2.items, ["Oil change", "Chain service"]);
assert.equal(service2.cost, 1200);
assert.equal(service2.nextServiceKm, 50000);
assert.equal(service2.notes, "Run-in service.");

// ---- ride ----
const ride = {
  id: "r1",
  bikeId: "bk1",
  date: "2026-09-03",
  route: "Bangalore to Mysore",
  distanceKm: 245.5,
  odometer: 42500,
  avgSpeedKmh: 68,
  notes: "Heavy rain sections.",
};
const rideMd = rideToMarkdown(ride, slug);
assert.match(rideMd, /^---\ntype: ride\n/);
assert.match(rideMd, /distance_km: 245\.5\n/);
const ride2 = markdownToRide(rideMd, slug);
assert.ok(ride2);
assert.equal(ride2.route, "Bangalore to Mysore");
assert.equal(ride2.distanceKm, 245.5);
assert.equal(ride2.avgSpeedKmh, 68);
assert.equal(ride2.notes, "Heavy rain sections.");

// ---- modification ----
const mod = {
  id: "m1",
  bikeId: "bk1",
  date: "2026-07-20",
  title: "Exhaust upgrade",
  description: "Aftermarket slip-on.",
  cost: 8500,
  installedBy: "Garage 42",
  notes: "Louder than expected.",
};
const modMd = modificationToMarkdown(mod, slug);
assert.match(modMd, /^---\ntype: modification\n/);
assert.match(modMd, /installed_by: Garage 42\n/);
const mod2 = markdownToModification(modMd, slug);
assert.ok(mod2);
assert.equal(mod2.title, "Exhaust upgrade");
assert.equal(mod2.cost, 8500);
assert.equal(mod2.installedBy, "Garage 42");
assert.equal(mod2.notes, "Louder than expected.");

// ---- checklist ----
const cl = {
  id: "c1",
  bikeId: "bk1",
  name: "Pre-ride check",
  items: ["Helmet", "Air pressure"],
  createdAt: "2026-09-01T10:00:00.000Z",
};
const clMd = checklistToMarkdown(cl);
assert.match(clMd, /^---\ntype: checklist\n/);
assert.match(clMd, /name: Pre-ride check\n/);
assert.match(clMd, /items: Helmet, Air pressure\n/);
const cl2 = markdownToChecklist(clMd);
assert.ok(cl2);
assert.equal(cl2.name, "Pre-ride check");
assert.deepEqual(cl2.items, ["Helmet", "Air pressure"]);

// ---- legacy marker format still readable ----
const legacyFuel = `# Fuel · 2026-09-01

<sub>Auto-generated by BikeLog · edit with care, format is strict</sub>

<!-- bikelog:fuel -->
- id: f9
- bikeId: bk1
- date: 2026-09-01T00:00:00.000Z
- odometer: 42381
- litres: 8.2
- pricePerLitre: 103
- totalCost: 844.6
- isFullTank: false
`;
const legacyFuelMd = markdownToFuel(legacyFuel);
assert.ok(legacyFuelMd, "legacy fuel still parses");
assert.equal(legacyFuelMd.id, "f9");
assert.equal(legacyFuelMd.odometer, 42381);
assert.equal(legacyFuelMd.litres, 8.2);
assert.equal(legacyFuelMd.totalCost, 844.6);

console.log("\nAll YAML frontmatter round-trips passed.");